import Layout from "../layout/layout";

function TermsConditions() {
    return (
        <Layout>
          <div className="max-w-4xl mx-auto px-6 py-12 ">
                <h1 className="text-3xl font-medium mb-10">Terms & Conditions</h1>
                <p className="mb-6 text-sm text-zinc-600 leading-6">
                This document is an electronic record in terms of Information Technology Act, 2000 and rules framed there under as applicable and the amended provisions relating to electronic records in various statutes in force as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.bellavitaluxury.co.in website. 
                </p>
        
                <h6 className="font-medium mb-4">USER AGREEMENT</h6>
                <p className="mb-6 text-sm text-zinc-600 leading-6">
                PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO BE BOUND BY ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT.
                </p>
        
                <p className="mb-5 text-sm text-zinc-600 leading-6">This Terms of Service Agreement (the Agreement) governs your use of this website, www.bellavitaluxury.co.in (Bella Vita Luxury) offers products for purchase on this Website, or your purchase of products available on this Website. This Agreement includes, and incorporates by this reference, the policies and guidelines referenced below.</p> 

                <p className="mb-5 text-sm text-zinc-600 leading-6">Bella Vita Luxury reserves the right to change or revise the terms and conditions of this Agreement at any time by posting any changes or a revised terms of the agreement on this Website. Any change or revision in this agreement will be reflected with date of change or revision on the top of this agreement. The changed or revised Agreement shall be effective immediately after it is posted on this Website. Your use of the Website or the services available on the website following posting any such changes or of a revised Agreement will constitute your acceptance of any such changes or revisions.</p> 

                <p className="mb-5 text-sm text-zinc-600 leading-6">Bella Vita Luxury encourages you to review these terms of user Agreement whenever you visit the Website to make sure that you understand the terms and conditions governing use of the Website. This Agreement does not alter in any way the terms or conditions of any other written agreement you may have with Bella Vita Luxury for other products or services. If you do not agree to this Agreement (including any referenced policies or guidelines), please immediately terminate your use of the Website which includes the services available on the same. By implicitly or expressly accepting these Terms of Use, you also accept and agree to be bound by Bella Vita Luxury Policies (including but not limited to Privacy Policy) as amended from time to time. If you would like to print this Agreement, please click the print button on your browser toolbar.</p> 

                <div className="mt-15">
                    <h6 className="font-medium mb-4 uppercase">Important Disclaimers</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                        The following disclaimers are essential for determining any relationship between You and Bella Vita Luxury for your use of any services on the website:
                    </p>

                    <ul className="list-disc pl-5 text-gray-700 space-y-3">
                        <li className="text-sm text-zinc-600 leading-6">
                        Bella Vita Luxury, its associates, affiliates, and service providers and technology partners make no representations or warranties about the accuracy, reliability, completeness, and/or timelines of any content, information, software, text, graphics, links, or communications provided on or through the use of the Website or that the operation of the Website will be error-free and/or uninterrupted.
                        </li>

                        <li className="text-sm text-zinc-600 leading-6">
                        You understand, agree, and acknowledge that Bella Vita Luxury uses third-party service providers to store and process your personal information and other data you provide (as more specifically identified in the Privacy Policy). Such third parties may store and process this data in a country or state that may not have jurisdiction over you. Bella Vita Luxury provides no guarantee or assurance that such third-party service providers will protect your personal information and is not liable for any actions, omissions, misconduct, fraud, or negligence by these third parties.
                        </li>

                        <li className="text-sm text-zinc-600 leading-6">
                        You acknowledge that Bella Vita Luxury will not be liable for any claims regarding financial losses, mental distress, repayments, or damages arising due to third-party breaches, hacking, viruses, or security breaches beyond our control. Bella Vita Luxury does not guarantee security in such cases until the website is fully restored to normal.
                        </li>
                    </ul>

                    <p className="mb-8 mt-5 text-sm text-zinc-600 leading-6">
                        You agree that the aforesaid disclaimers shall be in addition to any other disclaimers given in this User Agreement.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">MEMBERSHIP ELEGIBILITY</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    In order to use the service of Bella Vita Luxury through website you may use guest login or you may create your own Bella Vita Luxury account to use certain Bella Vita Luxury Services, and you may be required to be logged in to the account and have a valid payment method associated with it. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your account, and you agree to accept responsibility for all activities that occur under your account or password. To create your Bella Vita Luxury account, you must be eligible to enter into contract under Indian Contract Act, 1872. “Incompetent persons” under Indian Contract Act, 1872 are not eligible for Bella Vita Luxury account. Any minor i.e. a person below the age of 18 years can use the website and transact only through its legal guardians or Parent. Bella Vita Luxury reserves the right to terminate your account / refuse to provide its services if it is discovered the person using the website and making transaction is an “Incompetent person” under Indian Contract Act, 1872 who cannot enter into Contract. Any person who create account with Bella Vita Luxury will be called/referred to as Registered User.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">YOUR ACCOUNT & REGISTRATION OBLIGATIONS</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    If you use the Website as a Registered User, you are responsible for maintaining the confidentiality of your User ID and Password. You are responsible for all activities that occur under your User ID and Password. You agree, inter alia, to provide true, accurate, current and complete information about yourself as prompted by Website registration form or provided by You as a Visitor. If you provide any information that is untrue, inaccurate, not current or incomplete or Bella Vita Luxury has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the present terms of use agreement, Bella Vita Luxury  has the right to indefinitely suspend or terminate or block access of your membership with the Website and refuse to provide you with access to the Website and to provide it services.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">ELECTRONIC COMMUNICATIONS</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    When You use the Website or send emails or other data, information or communication to us, you agree and understand that You are communicating with us through electronic records and You consent to receive communications via electronic records from us periodically and as and when required. We may communicate with you by email or by any other mode of communication, electronic or otherwise. You can unsubscribe to any such emails or newsletters when there is an option available to you as per the terms mentioned in the privacy policy.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">USE OF PRODUCTS AND SERVICES</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    The products and services provided by Bella Vita Luxury on this website are for personal use only. Selling or reselling of products and services obtained through Bella Vita Luxury website is completely prohibited and Bella Vita Luxury  reserves its right to take appropriate legal action in adverse situation. Please note that we can call our customers and use their email id for calling purposes regarding order and tracking queries and for marketing campaigns.
                    </p>


                    <p className="mb-5  mt-10 text-sm text-zinc-600 leading-6">
                    Our products are non-returnable due to hygiene and personal care nature of the product.
                    </p>


                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    However, in the unlikely event of damaged, defective or different item delivered to you, or regarding the delivery kindly contact us in 24 hrs.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">FEES AND SERVICES</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    Membership on this website is free. Bella Vita Luxury does not charge for browsing and purchasing the product from this website except for the sale price of the product, applicable taxes as per the laws of India as well as the delivery charges wherever they are applicable. If you purchase any product from Bella Vita Luxury then you are obligatory to make its payment of charges as per Bella Vita Luxury payment policies. If you do not make payment or refuse to make payment of charges after purchasing product or services from Bella Vita Luxury  then Bella Vita Luxury reserves the right to annul the order or not to deliver the said product or to take measures like issuance of warning, temporarily /indefinitely suspend or terminate Your membership of the Website and refuse to provide You with access to all current and future use of the Website in case of non-payment of fees by You to www.bellavitaluxury.co.in and also reserves the right to take legal action which is permissible in law for recovery of the payments in case of non- payment of charges.
                    </p>

                </div>

                <div className="mt-15">
                    <h6 className="font-medium mb-4 uppercase">Use of the Website</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                        By using this website, you agree, undertake, and confirm that your use of the Website shall be strictly governed by the following binding principles:
                    </p>

                    <ul className="list-disc pl-5 mb-5 text-sm text-zinc-600 leading-6">
                        <li>You are solely responsible for your information.</li>
                        <li>You shall not host, display, upload, modify, publish, transmit, update, or share any information that : - </li>
                    </ul>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">- Belongs to some other person to which You do not have any right to.</p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">
                        - Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986.
                        </p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">- Harm minors in any way.</p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">- Violates any law for the time being in force.</p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">
                        -  Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
                        </p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">-  Violate any right of the Bella Vita Luxury or its representatives.</p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">
                        - You will not copy any content of this website, which is the proprietary interest of Bella Vita Luxury, copying of which may violates Intellectual Property Rights of Bella Vita Luxury .
                        </p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">- You will not use the details available on the website to mislead any third person.</p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">-  You will not write anything about Bella Vita Luxury on any social networking or post any of its content without the permission of Bella Vita Luxury .
                        </p>
                        <p className="mb-3 text-sm text-zinc-600 leading-6">
                        - You will not engage into infringement of the trademark of Bella Vita Luxury by adopting or using the mark Bella Vita Luxury or any mark wherein the mark Bella Vita Luxury forms one of the essential feature.
                        </p>
                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">LIMITATION OF LIABILITY</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    In no event Bella Vita Luxury, be liable for any indirect, incidental, special, incidental, consequential, punitive or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the Website, its services or this agreement (however arising, including negligence or under torts or under public policy).
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">INDEMNITY</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    You shall fully indemnify, keep indemnified, defend and hold harmless Bella Vita Luxury  its owners, licensees, subsidiaries, affiliates, third-parties and their respective shareholders, officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of this terms of use or any rules and policies contained herein, or your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.You also agree to indemnify us for any loss, damages, or costs, including reasonable attorneys’ fees, resulting from your use of software robots, spiders, crawlers, or similar data gathering and extraction tools, or any other action you take that imposes an unreasonable burden or load on our infrastructure.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">DISPUTE RESOLUTIONS</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    Generally, transactions are conducted smoothly on www.bellavitaorganic.com. But in case if any issue arises then at www.bellavitaluxury.co.in , we have a Dispute Resolution process in order to resolve disputes amicably between Buyers and Bella Vita Luxury. A ‘Dispute’ can be defined as a disagreement between a Buyer and Bella Vita Luxury in connection with a transaction on the Website. At www.bellavitaluxury.co.in you can register your grievance at customer care no. or you can write to us at shop@bellavitaorganic.com Bella Vita Luxury will make its best possible effort to to settle the issue amicably before reaching out to the complainant and try to amicably resolve the matter prior to taking any legal recourse or defending the same.
                    </p>

                </div>

                <div className="mt-15">
                    <h2 className="font-medium mb-4 uppercase">
                        Report an Intellectual Property Right Violation
                    </h2>
                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                        If you believe your intellectual property rights have been violated in any manner through the website, please write to us at{" "}
                        <a href="mailto:shop@bellavitaorganic.com"  className="underline">shop@bellavitaorganic.com</a>
                        . Bella Vita Luxury will make its best efforts to safeguard your interest.However, Bella Vita Luxury will not be liable for any violation of your Intellectual Property Rights caused by third-party goods or services sold on the Bella Vita Luxury website. Additionally, in the event of any claim regarding intellectual property violations against Bella Vita Luxury, the company reserves the right to defend itself as it deems appropriate.
                    </p>
                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">GOVERNING LAW / JURISICTIONAL ISSUE</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    This User Agreement and all the rules and policies contained herein and any of Your usage of Website and Your dealings with Bella Vita Luxury  shall be governed and construed in accordance with the laws of India subject to the exclusive jurisdiction of courts at Gurgaon, India.
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">Bella Vita Luxury  – GRIEVANCE OFFICER</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    This page is published and shall be construed in accordance with the provisions of Rule 3(11) of the Information Technology (Intermediaries Guidelines) Rules, 2011 (“IT Rules”) that requires publishing the name of the Grievance Officer and his/her contact details on the website, such that users or any victim who suffers as a result of a violation of Rule 3 (outlined in our Privacy Policy and Terms of Use) by any other person, can notify their complaints to us.
                    </p>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    Further, as per Rule 3(4) of the IT Rules, the Grievance Officer shall acknowledge or respond to Your communication of violation of Rule 3, by any other person, within 36 (thirty-six) hours, and the complaints shall be redressed within 1 (one) month from the date of receipt of the complaint.
                    </p>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    Accordingly, the Grievance Officer for the purpose of Your personal delicate information as governed by the Privacy Policy is:
                    </p>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    Name:      Aakash Anand
                    </p>

                </div>

                <div className="mt-15">

                    <h6 className="font-medium mb-4 uppercase">GENERAL</h6>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    None of the provisions of the User Agreement shall be deemed to constitute a partnership or agency between you and Bella Vita Luxury  and you shall have no authority to bind Bella Vita Luxury  in any manner whatsoever.
                    </p>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    If any clause of the Terms of use Agreement shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the User Agreement.
                    </p>

                    <p className="mb-5 text-sm text-zinc-600 leading-6">
                    This Agreement sets forth the entire understanding and agreement between You and Bella Vita Luxury  with respect to the subject matter hereof. You cannot assign or otherwise transfer this User Agreement, or any rights granted hereunder to any third party. Shopbrave.in may transfer its rights and obligations (also known as “assign”) under this Agreement without Your prior express consent, provided that www.bellavitaluxury.co.in  assigns the Agreement on the same terms. Bella Vita Luxury  reserve the right, at its sole discretion, to change these Terms and Conditions at any time by posting the changes on the website. Any changes are effective immediately upon posting to the Site. Your continued use of the website thereafter constitutes your agreement to all such changed Terms and Conditions.
                    </p>

                    <p className="mt-15 text-sm text-zinc-600 leading-6">
                    Disclaimer: Bella Vita Luxury  personal care products are based on natural and Ayurvedic formulations. Despite the fact that tremendous endeavors are made and safeguards are taken to deliver the items totally alright for human use, it is conceivable that specific fixings may make hypersensitive responses for certain people or unfavorably influence people with prior ailments. Please make yourself aware of the ingredients and usage instructions accompanying each of our products to make sure that they are safe for you to use. It will be your sole responsibility to take proper precaution/ professional medical/ dermatological advice before using any of our personal care products that you may be allergic to. You agree that Bella Vita Luxury  will not be responsible or liable for any product related issues, including without limitation any allergic reactions to you on account of usage of our products. For any buys made through www.bellavitaorganic.com, you will entitled to the conditions provided in more detail with the product packaging.
                    </p>

                </div>
            </div>
      </Layout>
    );
  }
  export default TermsConditions